version: '3.8'

services:
  users-service:
    build: ./users-service
    ports:
      - "5001:5000"
    networks:
      - ecom-network

  products-service:
    build: ./products-service
    ports:
      - "5002:5000"
    networks:
      - ecom-network

  orders-service:
    build: ./orders-service
    ports:
      - "5003:5000"
    networks:
      - ecom-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "5004:5000"
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge
