version: '3.8'

services:
  users-service:
    build: ./users-service
    ports:
      - "5001:5000"
    networks:
      - ecom-network
    environment:
      MONGO_URI: "mongodb+srv://neave:a5pO4sEvRMmTQrJO@ecom-microsystems.8f8el.mongodb.net/?retryWrites=true&w=majority&appName=ecom-microsystems"

  products-service:
    build: ./products-service
    ports:
      - "5002:5000"
    networks:
      - ecom-network
    environment:
      MONGO_URI: "mongodb+srv://neave:a5pO4sEvRMmTQrJO@ecom-microsystems.8f8el.mongodb.net/?retryWrites=true&w=majority&appName=ecom-microsystems"

  orders-service:
    build: ./orders-service
    ports:
      - "5003:5000"
    networks:
      - ecom-network
    environment:
      MONGO_URI: "mongodb+srv://neave:a5pO4sEvRMmTQrJO@ecom-microsystems.8f8el.mongodb.net/?retryWrites=true&w=majority&appName=ecom-microsystems"

  inventory-service:
    build: ./inventory-service
    ports:
      - "5004:5000"
    networks:
      - ecom-network
    environment:
      MONGO_URI: "mongodb+srv://neave:a5pO4sEvRMmTQrJO@ecom-microsystems.8f8el.mongodb.net/?retryWrites=true&w=majority&appName=ecom-microsystems"

  frontend:
    build:
      context: ./ecom-frontend
    ports:
      - "3000:3000"
    networks:
      - ecom-network
    command: ["npm", "start", "--", "--host", "0.0.0.0"]

networks:
  ecom-network:
    driver: bridge
