version: '3.8'

services:
  users-service:
    build: ./users-service
    ports:
      - "5001:5000"
    networks:
      - ecom-network
    environment:
      MONGO_URI: "mongodb+srv://neave:a5pO4sEvRMmTQrJO@ecom-microsystems.8f8el.mongodb.net/?retryWrites=true&w=majority&appName=ecom-microsystems"
      TESTING: "false"

  products-service:
    build: ./products-service
    ports:
      - "5002:5000"
    networks:
      - ecom-network
    environment:
      MONGO_URI: "mongodb+srv://neave:a5pO4sEvRMmTQrJO@ecom-microsystems.8f8el.mongodb.net/?retryWrites=true&w=majority&appName=ecom-microsystems"
      TESTING: "false"

  orders-service:
    build: ./orders-service
    ports:
      - "5003:5000"
    networks:
      - ecom-network
    environment:
      MONGO_URI: "mongodb+srv://neave:a5pO4sEvRMmTQrJO@ecom-microsystems.8f8el.mongodb.net/?retryWrites=true&w=majority&appName=ecom-microsystems"
      TESTING: "false"

  inventory-service:
    build: ./inventory-service
    ports:
      - "5004:5000"
    networks:
      - ecom-network
    environment:
      MONGO_URI: "mongodb+srv://neave:a5pO4sEvRMmTQrJO@ecom-microsystems.8f8el.mongodb.net/?retryWrites=true&w=majority&appName=ecom-microsystems"
      TESTING: "false"

networks:
  ecom-network:
    driver: bridge
